### ISSUE TITLE
Pay.ir Test Api Token Issue

### ISSUE THREAD

**Issue by taheri79** [paydotir/php-sdk#1]
This bug is related to **Pay.ir** servers but I suggested to make the issue here
if you use _'test'_ as your _Api Token_ to request Pay.ir servers, you won't receive any status in respawn also doesn't throw exceptions. And Its a  solution for Developers Like me who wanted to Use _Pay.ir_ services or ether _php-sdk_

**Comment by saeedvaziry** [comment]
Already tested this and haven't seen any issues.
`test` APIs working fine and returning token. Here is a sample code you can test it after installing this package:

```php
$gateway = new \Payir\SDK\Services\Gateway('test');
$send = $gateway->send(10000, "https://callback-url", []);
$paymentUrl = "https://pay.ir/pg/$send->token";
print_r($paymentUrl);
```
